<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Venezuela',
                'iso2' => 'VE',
                'iso3' => 'VEN',
                'phone_code' => '+58',
                'capital' => 'Caracas',
                'region' => 'América del Sur',
                'flag_url' => '/flags/ve.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-VE',
                'currency_name' => 'Bolívar Soberano',
                'currency_code' => 'VES',
                'currency_symbol' => 'Bs',
                'currency_format' => '#,##0.00', // opcional
                'exchange_rate_to_usd' => 0.000012,
                'exchange_rate_from_api' => 0.000012,
                'tax_rate' => 16.00,
                'tax_included_in_price' => false,
                'timezone' => 'America/Caracas',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'after',
                'is_active' => true,
            ],
            [
                'name' => 'Colombia',
                'iso2' => 'CO',
                'iso3' => 'COL',
                'phone_code' => '+57',
                'capital' => 'Bogotá',
                'region' => 'América del Sur',
                'flag_url' => '/flags/co.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-CO',
                'currency_name' => 'Peso Colombiano',
                'currency_code' => 'COP',
                'currency_symbol' => '$',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 0.000250,
                'exchange_rate_from_api' => 0.000250,
                'tax_rate' => 19.00,
                'tax_included_in_price' => true,
                'timezone' => 'America/Bogota',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'México',
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'phone_code' => '+52',
                'capital' => 'Ciudad de México',
                'region' => 'América del Norte',
                'flag_url' => '/flags/mx.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-MX',
                'currency_name' => 'Peso Mexicano',
                'currency_code' => 'MXN',
                'currency_symbol' => '$',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 0.050000,
                'exchange_rate_from_api' => 0.050000,
                'tax_rate' => 16.00,
                'tax_included_in_price' => false,
                'timezone' => 'America/Mexico_City',
                'currency_thousand_separator' => ',',
                'currency_decimal_separator' => '.',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'España',
                'iso2' => 'ES',
                'iso3' => 'ESP',
                'phone_code' => '+34',
                'capital' => 'Madrid',
                'region' => 'Europa',
                'flag_url' => '/flags/es.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-ES',
                'currency_name' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 1.070000,
                'exchange_rate_from_api' => 1.070000,
                'tax_rate' => 21.00,
                'tax_included_in_price' => true,
                'timezone' => 'Europe/Madrid',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Estados Unidos',
                'iso2' => 'US',
                'iso3' => 'USA',
                'phone_code' => '+1',
                'capital' => 'Washington D.C.',
                'region' => 'América del Norte',
                'flag_url' => '/flags/us.svg',
                'language_name' => 'Inglés',
                'language_code' => 'en',
                'locale' => 'en-US',
                'currency_name' => 'Dólar Estadounidense',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 1.000000,
                'exchange_rate_from_api' => 1.000000,
                'tax_rate' => 0.00,
                'tax_included_in_price' => false,
                'timezone' => 'America/New_York',
                'currency_thousand_separator' => ',',
                'currency_decimal_separator' => '.',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Argentina',
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'phone_code' => '+54',
                'capital' => 'Buenos Aires',
                'region' => 'América del Sur',
                'flag_url' => '/flags/ar.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-AR',
                'currency_name' => 'Peso Argentino',
                'currency_code' => 'ARS',
                'currency_symbol' => '$',
                'currency_format' => '#.##0,00',
                'exchange_rate_to_usd' => 0.001100,
                'exchange_rate_from_api' => 0.001100,
                'tax_rate' => 21.00,
                'tax_included_in_price' => true,
                'timezone' => 'America/Argentina/Buenos_Aires',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Chile',
                'iso2' => 'CL',
                'iso3' => 'CHL',
                'phone_code' => '+56',
                'capital' => 'Santiago',
                'region' => 'América del Sur',
                'flag_url' => '/flags/cl.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-CL',
                'currency_name' => 'Peso Chileno',
                'currency_code' => 'CLP',
                'currency_symbol' => '$',
                'currency_format' => '#.##0',
                'exchange_rate_to_usd' => 0.001120,
                'exchange_rate_from_api' => 0.001120,
                'tax_rate' => 19.00,
                'tax_included_in_price' => true,
                'timezone' => 'America/Santiago',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 0, // CLP no suele usar decimales
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Perú',
                'iso2' => 'PE',
                'iso3' => 'PER',
                'phone_code' => '+51',
                'capital' => 'Lima',
                'region' => 'América del Sur',
                'flag_url' => '/flags/pe.svg',
                'language_name' => 'Español',
                'language_code' => 'es',
                'locale' => 'es-PE',
                'currency_name' => 'Sol Peruano',
                'currency_code' => 'PEN',
                'currency_symbol' => 'S/',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 0.265000,
                'exchange_rate_from_api' => 0.265000,
                'tax_rate' => 18.00,
                'tax_included_in_price' => true,
                'timezone' => 'America/Lima',
                'currency_thousand_separator' => ',',
                'currency_decimal_separator' => '.',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Brasil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'phone_code' => '+55',
                'capital' => 'Brasilia',
                'region' => 'América del Sur',
                'flag_url' => '/flags/br.svg',
                'language_name' => 'Portugués',
                'language_code' => 'pt',
                'locale' => 'pt-BR',
                'currency_name' => 'Real Brasileño',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'currency_format' => '#.##0,00',
                'exchange_rate_to_usd' => 0.180000,
                'exchange_rate_from_api' => 0.180000,
                'tax_rate' => 0.00,
                'tax_included_in_price' => false,
                'timezone' => 'America/Sao_Paulo',
                'currency_thousand_separator' => '.',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
            [
                'name' => 'Francia',
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'phone_code' => '+33',
                'capital' => 'París',
                'region' => 'Europa',
                'flag_url' => '/flags/fr.svg',
                'language_name' => 'Francés',
                'language_code' => 'fr',
                'locale' => 'fr-FR',
                'currency_name' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_format' => '#,##0.00',
                'exchange_rate_to_usd' => 1.070000,
                'exchange_rate_from_api' => 1.070000,
                'tax_rate' => 20.00,
                'tax_included_in_price' => true,
                'timezone' => 'Europe/Paris',
                'currency_thousand_separator' => ' ',
                'currency_decimal_separator' => ',',
                'currency_decimal_digits' => 2,
                'currency_symbol_position' => 'before',
                'is_active' => true,
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
