// 🚀 Auto-generated by generate-layout-registry.js
// ❌ DO NOT EDIT MANUALLY - Changes will be overwritten
// ✅ Run: npm run generate:layouts

export const layoutRegistry = {
  '2026/Home/HomeLayout': () => import('./2026/Home/HomeLayout.jsx'),
  '2026/SuperAdmin/SuperAdminDashboardLayout': () => import('./2026/SuperAdmin/SuperAdminDashboardLayout.jsx'),
  '2026/User/UserDashboardLayout': () => import('./2026/User/UserDashboardLayout.jsx'),
  'AuthenticatedLayout': () => import('./AuthenticatedLayout.jsx'),
  'BaseLayout': () => import('./BaseLayout.jsx'),
  'GuestLayout': () => import('./GuestLayout.jsx'),
  'MainLayout': () => import('./MainLayout.jsx'),
  'RegistrationLayout': () => import('./RegistrationLayout.jsx'),
  'SuperAdminLayout': () => import('./SuperAdminLayout.jsx'),
  'TestLayout': () => import('./TestLayout.jsx'),
};
